# Generated by Django 3.0.7 on 2020-11-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20201117_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reproductionnum',
            name='adj',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='reproductionnum',
            name='infect',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='reproductionnum',
            name='state',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
