# Generated by Django 3.0.7 on 2020-11-17 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20201117_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coviddata',
            old_name='ec',
            new_name='EC',
        ),
        migrations.RenameField(
            model_name='coviddata',
            old_name='fs',
            new_name='FS',
        ),
        migrations.RenameField(
            model_name='coviddata',
            old_name='gp',
            new_name='GP',
        ),
        migrations.RenameField(
            model_name='coviddata',
            old_name='kzn',
            new_name='KZN',
        ),
        migrations.RenameField(
            model_name='coviddata',
            old_name='lp',
            new_name='LP',
        ),
        migrations.RenameField(
            model_name='coviddata',
            old_name='mp',
            new_name='MP',
        ),
        migrations.RenameField(
            model_name='coviddata',
            old_name='nc',
            new_name='NC',
        ),
        migrations.RenameField(
            model_name='coviddata',
            old_name='nw',
            new_name='NW',
        ),
        migrations.RenameField(
            model_name='coviddata',
            old_name='wc',
            new_name='WC',
        ),
    ]
