# Generated by Django 3.0.7 on 2020-11-29 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20201117_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coviddata',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='coviddata',
            old_name='source',
            new_name='Source',
        ),
        migrations.RenameField(
            model_name='coviddata',
            old_name='total',
            new_name='Total',
        ),
        migrations.RenameField(
            model_name='coviddata',
            old_name='unknown',
            new_name='Unknown',
        ),
        migrations.RenameField(
            model_name='coviddata',
            old_name='var',
            new_name='Var',
        ),
        migrations.RenameField(
            model_name='reproductionnum',
            old_name='adj',
            new_name='Adj',
        ),
        migrations.RenameField(
            model_name='reproductionnum',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='reproductionnum',
            old_name='high',
            new_name='High',
        ),
        migrations.RenameField(
            model_name='reproductionnum',
            old_name='infect',
            new_name='Infect',
        ),
        migrations.RenameField(
            model_name='reproductionnum',
            old_name='low',
            new_name='Low',
        ),
        migrations.RenameField(
            model_name='reproductionnum',
            old_name='state',
            new_name='Province',
        ),
        migrations.RenameField(
            model_name='reproductionnum',
            old_name='rt',
            new_name='Rt',
        ),
        migrations.RenameField(
            model_name='reproductionnum',
            old_name='var',
            new_name='Var',
        ),
    ]
