# Generated by Django 3.1.5 on 2021-02-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20201129_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coviddata',
            name='Source',
            field=models.CharField(max_length=400),
        ),
    ]
